INSERT INTO `inv_institutions` (`Id_institution`,`institution`,`abbreviation`,`contact`,`contact_job`,`address`,`phone`,`fax`,`cod_city`,`AA`,`country`,`web_page`,`email_1`,`email_2`,`observations`) VALUES 
 (1,'Centro Control Contaminación del Pacífico','CCCP','CF Ricardo Molares Babra','Director',NULL,NULL,NULL,234256,'187','CO','http://www.cccp.org.co','cccp@dimar.mil.co','jefcccp@dimar.mil.co',NULL),
 (3,'Centro de Investigaciones Oceanograficas e Hidrograficas','CIOH',NULL,NULL,NULL,NULL,NULL,24792,NULL,'CO','http://www.cioh.org.co','cioh@dimar.mil.co','jdihid@cioh.org.co',NULL),
 (5,'Comisión Colombiana del Océano','CCO','Julián Augusto Reyna','Secretario','Carrera 54 No. 26-50 piso 4','2220436','2220421',16336,NULL,'CO','http://www.cco.gov.co','seco@cco.gov.co ','jreyna@dimar.mil.co',NULL),
 (11,'Dirección General Marítima','DIMAR','Contralmirante Jairo Javier Peña','Director','Carrera 54 No. 26-50 Of. 102','2200490',NULL,16336,NULL,'CO','http://www.dimar.mil.co','dimar@dimar.mil.co',NULL,NULL),
 (13,'Escuela Naval de Cadetes \"Almirante Padilla\"','ENAP','Serguei Lonin','Investigador',NULL,NULL,NULL,24792,NULL,'CO','http://www.escuelanaval.edu.co/investiga.html ','gio@enap.edu.co ',NULL,NULL),
 (16,'Fundación Malpelo y otros Ecosistemas Marinos','FMALPELO','Sandra Bessudo','Directora','Cra. 11  No. 87-51  Local 4  Piso 2','6402114','6402110',16336,NULL,'CO','http://www.fundacionmalpelo.org/','sbessudo@fundacionmalpelo.org ',NULL,NULL),
 (18,'Fundación Yubarta','FYUB','Lilian Florez Gonzalez','Directora','Carrera 24F Oeste No. 3-110 Tejares de San Fernando','5585598','5585598',33465,NULL,'CO','http://www.aventurassubmarinas.com/yubarta.htm',NULL,NULL,NULL),
 (20,'Instituto de Hidrología, Meteorología y Estudios Ambientales','IDEAM',NULL,NULL,'Carrea 40 No. 20-30 Piso 6','3527160','3527160',16336,NULL,'CO','http://www.ideam.gov.co',NULL,NULL,NULL),
 (22,'Instituto de Investigaciones Marinas y Costeras \"José Benito Vives de Andreis\" ','INVEMAR',NULL,NULL,NULL,NULL,NULL,33465,NULL,'CO','http://www.invemar.org.co','gnavas@invemar.org.co','earteaga@invemar.org.co',NULL),
 (26,'Unidad Administrativa Especial del Sistema de Parques Nacionales Naturales','UAESPNN','Beatriz Beltrán','Directora','Avenida 3G  Norte No. 37N - 70 Prados del Norte','656124','553719',33465,NULL,'CO','http://www.parquesnacionales.gov.co/','bbeltranleon@yahoo.com',NULL,NULL),
 (28,'Universidad de Antioquia','UDEA',NULL,NULL,NULL,NULL,NULL,36185,NULL,'CO','http://gaia.udea.edu.co/','gaia@udea.edu.co',NULL,NULL),
 (29,'Universidad de Cartagena','UNICARTAGENA',NULL,NULL,NULL,NULL,NULL,24792,NULL,'CO','http://www.reactivos.com','quicomputacional@unicartagena.edu.co',NULL,NULL),
 (34,'Universidad del Cauca','UNICAUCA','Andrés José Castrillón Muñoz',NULL,'Carrera 2 No. 1A-25 Urbanización Caldas','8209860',NULL,48174,NULL,'CO','http://unicauca.edu.co/','andresj9@unicauca.edu.co ',NULL,NULL),
 (35,'Universidad del Magdalena','UNIMAGDALENA',NULL,NULL,NULL,NULL,NULL,49560,NULL,'CO','http://www.unimagdalena.edu.co','juan.gaitan@docente.unimagdalena.edu.co',NULL,NULL),
 (36,'Universidad del Tolima','UT',NULL,NULL,NULL,'2726139',NULL,49291,NULL,'CO','http://www.ut.edu.co/',NULL,NULL,NULL),
 (37,'Universidad del Valle','UNIVALLE','Alan Giraldo López','Profesor Asistente del Departamento de Biología','Calle 13  No. 100 - 00 Ciudad Universitaria Meléndez','3212100','3212100',33465,NULL,'CO','http://www.univalle.edu.co','agiraldo@univalle.edu.co ',NULL,NULL),
 (38,'Universidad EAFIT','EAFIT',NULL,NULL,NULL,NULL,NULL,49116,NULL,'CO','http://www.eafit.edu.co/','hermelin@eafit.edu.co',NULL,NULL),
 (40,'Universidad Militar Nueva Granada','UMNG',NULL,NULL,NULL,NULL,NULL,16336,NULL,'CO','http://www.umng.edu.co/',NULL,NULL,NULL),
 (41,'Universidad Nacional de Colombia - Sede Medellín','UNALMED',NULL,NULL,NULL,NULL,NULL,36185,NULL,'CO','http://www.unalmed.edu.co/','fmtoro@unalmed.edu.co',NULL,NULL),
 (42,'Universidad Nacional de Colombia','UNAL',NULL,NULL,NULL,NULL,NULL,16336,NULL,'CO','http://www.unal.edu.co/','frleiva@yahoo.es',NULL,NULL),
 (43,'Universidad Nacional de Colombia - Sede Manizales','UNAL',NULL,NULL,NULL,NULL,NULL,'48165',NULL,'CO','http://www.manizales.unal.edu.co/','fmejiaf@unal.edu.co',NULL,NULL),
 (49,'Armada de la República de Colombia','ARMADA',NULL,NULL,NULL,NULL,NULL,16336,NULL,'CO','http://www.armada.mil.co',NULL,NULL,NULL),
 (50,'Instituto Nacional de los Recursos Naturales Renovables y del Medio Ambiente','INDERENA',NULL,NULL,NULL,NULL,NULL,16336,NULL,'CO',NULL,NULL,NULL,'InstituciÃ³n no activa.'),
 (51,'Universidad de Nariño','UDENAR',NULL,NULL,NULL,NULL,NULL,49221,NULL,'CO','http//www.udenar.edu.co',NULL,NULL,NULL),
 (52,'xxxxxxxxxxxxxxxx','xxxxxxxxxxxxxx',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'CO','xxxxxxxxxxxxxxxxxxxxx',NULL,NULL,NULL),
 (53,'Universidad Jorge Tadeo Lozano','UNITADEO',NULL,NULL,NULL,NULL,NULL,16336,NULL,'CO','http://www.utadeo.edu.co',NULL,NULL,NULL),
 (54,'Comisión Colombiana de Oceanografía','CCO',NULL,NULL,NULL,NULL,NULL,16336,NULL,'CO',NULL,NULL,NULL,'InstituciÃ³n no activa. Actualmente conocida como ComisiÃ³n Colombiana del OcÃ©ano.'),
 (55,'Instituto Colombiano de Hidrología, Meteorología y Adecuación de Tierras','HIMAT',NULL,NULL,NULL,NULL,NULL,16336,NULL,'CO',NULL,NULL,NULL,'InstituciÃ³n no activa. Actualmente conocida como Instituto de HidrologÃ­a, MeteorologÃ­a y Estudios Ambientales (IDEAM)'),
 (56,'Diario El Espectador','ELESPECTADOR',NULL,NULL,NULL,NULL,NULL,16336,NULL,'CO','http://www.elespectador.com/',NULL,NULL,NULL),
 (57,'Smithsonian Tropical Research Institute','STRI',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'PA','http://www.stri.org/',NULL,NULL,NULL),
 (58,'National Oceanic and Atmospheric Administration','NOAA',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'US','http://www.noaa.gov/',NULL,NULL,NULL),
 (59,'Universidad Industrial de Santander','UIS',NULL,NULL,NULL,NULL,NULL,29935,NULL,'CO','http://www.uis.edu.co',NULL,NULL,NULL),
 (60,'Servicio Nacional de Aprendizaje','SENA',NULL,NULL,NULL,NULL,NULL,16336,NULL,'CO','http://www.sena.edu.co',NULL,NULL,NULL),
 (61,'Armada de la República de Venezuela','ARMADA',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'VE','http://www.armada.mil.ve/',NULL,NULL,NULL),
 (62,'Instituto Nacional de Pesca y Acuicultura de Colombia','INPA',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'CO',NULL,NULL,NULL,'Institución no activa.'),
 (63,'Pontificia Universidad Javeriana','JAVERIANA',NULL,NULL,NULL,NULL,NULL,16336,NULL,'CO','http://www.javeriana.edu.co/',NULL,NULL,NULL),
 (64,'Instituto Nacional de Pesca de Ecuador','INP',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'EC','http://www.inp.gov.ec',NULL,NULL,NULL),
 (65,'Instituto del Mar del Perú','IMARPE',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'PE','http://www.imarpe.gob.pe/',NULL,NULL,NULL),
 (66,'Fundación Universitaria de Popayán','FUP',NULL,NULL,NULL,NULL,NULL,48174,NULL,'CO','http://www.fup.edu.co/',NULL,NULL,NULL),
 (67,'Dirección de Hidrografía y Navegación de la Marina de Guerra del Perú','DHN',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'PE','http://www.dhn.mil.pe/',NULL,NULL,NULL),
 (68,'Instituto de Fomento Pesquero de Chile','IFOP',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'CH','http://www.ifop.cl/',NULL,NULL,NULL),
 (69,'Instituto Oceanográfico de la Armada de Ecuador','INOCAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'PE','http://www.inocar.mil.ec/',NULL,NULL,NULL),
 (70,'Universidad de La Salle','UNISALLE',NULL,NULL,NULL,NULL,NULL,16336,NULL,'CO','http://unisalle.lasalle.edu.co/',NULL,NULL,NULL),
 (71,'Instituto Colombiano para el Desarrollo Rural','INCODER',NULL,NULL,NULL,NULL,NULL,16336,NULL,'CO','http://www.incoder.gov.co/',NULL,NULL,NULL),
 (72,'Comisión Permanente del Pacífico Sur','CPPS',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'EC','http://www.cpps-int.org/',NULL,NULL,NULL),
 (73,'Diario El Tiempo','ELTIEMPO',NULL,NULL,NULL,NULL,NULL,16336,NULL,'CO','http://www.eltiempo.com/',NULL,NULL,NULL),
 (74,'Diario El País','ELPAIS',NULL,NULL,NULL,NULL,NULL,33465,NULL,'CO','http://www.elpais.com.co/',NULL,NULL,NULL),
 (75,'Fundación Omacha','OMACHA',NULL,NULL,NULL,NULL,NULL,16336,NULL,'CO','http://www.omacha.org/',NULL,NULL,NULL),
 (76,'Centro de Investigaciones Oceanográficas e Hidrográficas del Pacífico','CCCP',NULL,NULL,'Vía El Morro, Capitanía de Puerto Tumaco','57 2 7272637','57 2 7272637',234256,'187','CO','http://www.cccp.org.co','cccp@dimar.mil.co','jefcccp@dimar.mil.co','El nombre del CCCP cambió con el Decreto 5057 de 2009 del Ministerio de Defensa de Colombia'),
 (77,'Centro de Investigaciones Oceanográficas e Hidrográficas del Caribe','CIOH',NULL,NULL,'Barrio Bosque, Sector Manzanillo Escuela Naval','57 5 6694465','57 5 6694297',24792,NULL,'CO','http://www.cioh.org.co/','cioh@dimar.mil.co','jefcioh@dimar.mil.co','El nombre del CIOH cambió con el Decreto 5057 de 2009 del Ministerio de Defensa de Colombia'),
 (78,'Escuela Naval de Suboficiales  \"ARC Barranquilla\"','ENSB',NULL,NULL,NULL,NULL,NULL,29618,NULL,'CO','http://190.60.108.210/webensb/',NULL,NULL,NULL),
 (79,'Petróleo Brasilero','PETROBRAS',NULL,NULL,'Carrera 7 No. 71 – 21 Torre B Piso 17','57 1 3135000','57 1 3135000',16336,NULL,'CO','http://www.petrobras.com/es/paises/colombia/colombia.htm',NULL,NULL,NULL),
 (80,'Woods Hole Group do Brasil','WHG',NULL,NULL,'Rua Primeiro de março, No. 20 – grupo 2004, Parte, Centro, CEP 20010-000',NULL,NULL,16336,NULL,'CO','http://www.woodsholegroupbrasil.com',NULL,NULL,NULL),
 (81,'Dirección General Marítima y Portuaria','DIMAR',NULL,NULL,'Carrera 54 No. 26-50 Of. 102','57 1 2200490',NULL,16336,NULL,'CO','http://www.dimar.mil.co','dimar@dimar.mil.co',NULL,'A partir de 1984, con el Decreto 2324, se reorganizó la Dimar, como Dirección General Marítima');
