INSERT INTO `inv_chief_scientist` (`Id`,`initials`,`first_name`,`last_name`,`profession`,`cv_lac`,`job`,`institution`,`active`,`active_until`,`phone`,`fax`,`country`,`personal_web_page`,`e_mail_1`,`e_mail_2`) VALUES 
 ('1',NULL,'Alberto','Martínez',44,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('10',NULL,'Brian','Chatez',48,NULL,NULL,37,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('100',NULL,'Irene','Marín Jaramillo',21,NULL,NULL,37,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('101',NULL,'Beatriz','Beltrán León',21,NULL,NULL,26,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('102',NULL,'Luis','Zapata',21,NULL,NULL,62,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('103',NULL,'Alberto','Collazos',21,NULL,NULL,37,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('104',NULL,'Jorge','Pérez',39,NULL,NULL,42,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('105',NULL,'Margarita','Marín',46,NULL,NULL,56,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('106',NULL,'Francisco','Carranza',46,NULL,NULL,56,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('107',NULL,'Victor','Bermúdez',51,NULL,NULL,3,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('108',NULL,'Oscar','Quintana',51,NULL,NULL,3,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('109',NULL,'Francisco','Reyes',35,NULL,NULL,55,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('11',NULL,'Ovidio','Zúñiga',48,NULL,NULL,51,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('110',NULL,'Jaime','Ramírez',50,NULL,NULL,55,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('111',NULL,'Jairo','González',50,NULL,NULL,55,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('112',NULL,'Guillermo','Rendón',34,NULL,NULL,42,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('113',NULL,'Francisco','Hernández',34,NULL,NULL,42,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('114',NULL,'Walter','Navarro',20,NULL,NULL,42,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('115',NULL,'Gabriel','Jácome',20,NULL,NULL,57,NULL,NULL,NULL,NULL,'PA',NULL,'e-mail_1','e-mail_2'),
 ('116',NULL,'Ross','Robertson',20,NULL,NULL,57,NULL,NULL,NULL,NULL,'PA',NULL,'e-mail_1','e-mail_2'),
 ('117',NULL,'Juan Diego','López',20,NULL,NULL,57,NULL,NULL,NULL,NULL,'PA',NULL,'e-mail_1','e-mail_2'),
 ('118',NULL,'Julio César','Escobar',20,NULL,NULL,37,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('119',NULL,'Wilfredo','Henao',20,NULL,NULL,37,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('12',NULL,'William','Aristizábal',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('120',NULL,'Raúl','Neira',53,NULL,NULL,37,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('121',NULL,'Nelson','Fernández',20,NULL,NULL,53,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('122',NULL,'Javier','Díaz',20,NULL,NULL,53,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('123',NULL,'Zenaida','Vizcaíno',20,NULL,NULL,3,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('124',NULL,'Manuel','Osorio',NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('125',NULL,'Francisco','Benavides',38,NULL,NULL,55,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('126',NULL,'Carlos','Casas',52,NULL,NULL,55,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('127',NULL,'Manuel','Garzón',NULL,NULL,NULL,55,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('128',NULL,'Warren','Krug',NULL,NULL,NULL,58,NULL,NULL,NULL,NULL,'US',NULL,'e-mail_1','e-mail_2'),
 ('129',NULL,'Liliana','Posada',NULL,NULL,NULL,42,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('13',NULL,'Celso','Beltrán',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('130',NULL,'Nelson','Parodi Díaz',34,NULL,NULL,42,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('131',NULL,'Carlos Roberto','Arango',NULL,NULL,NULL,42,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('132',NULL,'Juan Carlos','Suárez',21,NULL,NULL,59,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('133',NULL,'Rosa Elena','Pinzón',21,NULL,NULL,59,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('134',NULL,'Jaime Eduardo','Mauna De los Reyes',20,NULL,NULL,37,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('135',NULL,'Marco Antonio','Vizcaíno',35,NULL,NULL,37,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('136',NULL,'Héctor','Ospina',49,NULL,NULL,3,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('137',NULL,'Hernando','Wiest',40,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('138',NULL,'Mauricio','Moreno',40,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('139',NULL,'Orlando','Lemus',38,NULL,NULL,55,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('14',NULL,'Daniel','Dossman',21,NULL,NULL,37,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('140',NULL,'Gloria','Cabrera',38,NULL,NULL,55,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('141',NULL,'Mario','Vacca',27,NULL,NULL,55,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('142',NULL,'Noel','Garzón',NULL,NULL,NULL,55,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('143',NULL,'Guillermo','Ardila',NULL,NULL,NULL,55,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('144',NULL,'José','Barreto',NULL,NULL,NULL,55,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('145',NULL,'José','Cruz',NULL,NULL,NULL,55,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('146',NULL,'Alejandro','Suárez',20,NULL,NULL,1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('147',NULL,'Clara','Barbos',20,NULL,NULL,1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('148',NULL,'José','Vélez',20,NULL,NULL,1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('149',NULL,'Julio','Vélez',NULL,NULL,NULL,37,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('15',NULL,'Rafael','García',NULL,NULL,NULL,52,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('150',NULL,'Rafael','Carazo B.',43,NULL,NULL,60,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('151',NULL,'Leonardo','Díaz B.',43,NULL,NULL,60,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('152',NULL,'Manuel','Coneo M.',43,NULL,NULL,60,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('153',NULL,'Luis','Coneo M.',43,NULL,NULL,60,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('154',NULL,'Carlos','Escamilla S.',43,NULL,NULL,60,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('155',NULL,'Abel F.','Silva',43,NULL,NULL,60,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('156',NULL,'Elis','García G.',43,NULL,NULL,60,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('157',NULL,'Didier','González C.',43,NULL,NULL,60,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('158',NULL,'Jorgan A.','Aroldo',43,NULL,NULL,60,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('159',NULL,'Obando B.','Ekener',43,NULL,NULL,60,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('16',NULL,'Felipe','Hawking',NULL,NULL,NULL,52,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('160',NULL,'Rolando ','Tovar A.',43,NULL,NULL,60,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('161',NULL,'Augusto','Ruiz C.',43,NULL,NULL,60,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('162',NULL,'Ricardo','Quintero Serpa',20,NULL,NULL,3,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('163',NULL,'Javier','Holguín',55,NULL,NULL,3,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('164',NULL,'Eduardo','Montagut',40,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('165',NULL,'Elías','Blanco',55,NULL,NULL,1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('166',NULL,'Daniel','Rodríguez Godoy',NULL,NULL,NULL,61,NULL,NULL,NULL,NULL,'VE',NULL,'e-mail_1','e-mail_2'),
 ('167',NULL,'Fredy','Pretil',NULL,NULL,NULL,62,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('168',NULL,'Wilson','González',NULL,NULL,NULL,62,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('169',NULL,'Martha','Lasso',38,NULL,NULL,55,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('17',NULL,'José','Lagos',NULL,NULL,NULL,51,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('170',NULL,'Jorge','Moreno',38,NULL,NULL,55,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('171',NULL,'Luis','Ramírez',48,NULL,NULL,42,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('172',NULL,'Norma','Grimaldo',21,NULL,NULL,42,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('173',NULL,'Gladis','Arguello',21,NULL,NULL,42,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('174',NULL,'Jackeline','Boada',21,NULL,NULL,42,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('175',NULL,'Rito Ernesto','Gómez',40,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('176',NULL,'Alonso','Marrugo',48,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('177',NULL,'Alex René','Pineda Devia',36,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('178',NULL,'Constanza','Soler',54,NULL,NULL,1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('179',NULL,'Jhon','Álvarez',49,NULL,NULL,1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('18',NULL,'Jorge','Morales',NULL,NULL,NULL,51,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('180',NULL,'Cesar','Pineda',49,NULL,NULL,1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('181',NULL,'Héctor','Guevara',49,NULL,NULL,1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('183',NULL,'Fabián','Molina',49,NULL,NULL,1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('184',NULL,'Carlos','Portillo',26,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('186',NULL,'Lucía','Garcés',NULL,NULL,NULL,53,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('187',NULL,'Liliana','Medina Campos',21,NULL,NULL,53,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('188',NULL,'Julián Augusto','Reyna Moreno',40,NULL,NULL,1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('189',NULL,'César','Pinto',49,NULL,NULL,1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('19',NULL,'Mauro','Recalde',NULL,NULL,NULL,51,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('190',NULL,'Nairo Antonio','Montenegro',49,NULL,NULL,1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('191',NULL,'Jorge','Batista',49,NULL,NULL,1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('192',NULL,'Alejandro','Sarmiento',49,NULL,NULL,1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('193',NULL,'Juan Carlos','Barraza',49,NULL,NULL,1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('194',NULL,'Janeth','Acevedo',NULL,NULL,'Archivo Capitanía de Puerto',1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('195',NULL,'Fulleda','León',49,NULL,NULL,1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('196',NULL,'Fredy','Cervantes',49,NULL,NULL,1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('197',NULL,'Robinson Fidel','Casanova',48,NULL,'Jefe Laboratorio de Química',1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('198',NULL,'Juan','Herrera Leal',40,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('199',NULL,'Carlos','Moreno',49,NULL,NULL,1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('2',NULL,'Gabriel','Acevedo',20,NULL,NULL,50,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('20',NULL,'Marcos','Torres',NULL,NULL,NULL,52,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('200',NULL,'Yuber','Paúl',49,NULL,NULL,1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('201',NULL,'Salomón','Salazar',NULL,NULL,NULL,51,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('202',NULL,'Edgard Enrico','Cabrera Luna',40,NULL,NULL,1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('203',NULL,'Jairo Javier','Peña',40,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('204',NULL,'Carlos','Vergara',49,NULL,NULL,63,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('205',NULL,'Ramón','López',49,NULL,NULL,1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('206',NULL,'Diana','Molano',30,NULL,NULL,1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('207',NULL,'Gustavo','Camacho Guerrero',40,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('208',NULL,'Valery','Tchantsev',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('209',NULL,'Julio','Vargas Gómez',40,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('21',NULL,'Guillermo','Vásquez',NULL,NULL,NULL,37,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('210',NULL,'José Fernando','Jiménez',33,NULL,NULL,42,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('211',NULL,'Carlos Ramón','Barrera',20,NULL,NULL,20,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('212',NULL,'Carlos','Fernández',NULL,NULL,NULL,51,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('213',NULL,'Mario','Guardo',49,NULL,NULL,1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('214',NULL,'Alexandra','Quiceno',NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('215',NULL,'Maria Fernanda','Barberi',47,NULL,NULL,1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('216',NULL,'Angélica','Chilito',NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('217',NULL,'Patricia','Macias',32,NULL,NULL,64,NULL,NULL,NULL,NULL,'EC',NULL,'e-mail_1','e-mail_2'),
 ('218',NULL,'Oscar','Fajardo',49,NULL,NULL,1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('219',NULL,'Diego Fernando','Guerrero Zorrilla',49,NULL,'DIMAR-División de Litorales y Areas Marinas',1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('22',NULL,'Vitelmo','Riveros Polanía',25,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('220',NULL,'Lewis','Cabeza Durango',49,NULL,NULL,1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('221',NULL,'Elcira','Delgado',20,NULL,NULL,65,NULL,NULL,NULL,NULL,'PE',NULL,'e-mail_1','e-mail_2'),
 ('222',NULL,'Luis Jesús','Otero Díaz',40,NULL,NULL,1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('223',NULL,'Demmys','Roso Sánchez',49,NULL,NULL,1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('224',NULL,'Rocío','Meneses Sánchez',23,NULL,NULL,66,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('225',NULL,'Julián','Uribe',20,NULL,NULL,53,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('226',NULL,'Lucía','Fonseca',20,NULL,NULL,1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('227',NULL,'Armando','De Lissa Bornachera',40,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('228',NULL,'Eric','Guayana Labrador',40,NULL,NULL,1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('229',NULL,'Ingrid','García Hansen',20,NULL,NULL,1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('23',NULL,'Pedro','Monsalve Angarita',40,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('230',NULL,'Andrea','Devis Morales',42,NULL,NULL,1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('231',NULL,'Jorge','Soler',NULL,NULL,NULL,20,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('232',NULL,'Edgar','Arteaga',20,NULL,NULL,22,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('233',NULL,'Carlos','Guerrero',NULL,NULL,NULL,67,NULL,NULL,NULL,NULL,'AU',NULL,'e-mail_1','e-mail_2'),
 ('234',NULL,'Miles','Hernán',20,NULL,NULL,68,NULL,NULL,NULL,NULL,'CH',NULL,'e-mail_1','e-mail_2'),
 ('235',NULL,'Bernardo','Benavides White',40,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('236',NULL,'Urbano','Rosas',44,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('237',NULL,'Carolina','López',44,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('238',NULL,'Alejandro','Sanín',44,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('239',NULL,NULL,'Robledo',44,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('24',NULL,'Gustavo','Fajardo Méndez',40,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('240',NULL,'Cesar','Garzón',49,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('241',NULL,'Rico','Wilson',49,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('242',NULL,'Nilson Yan','Rueda',49,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('243',NULL,'Sandro','Babativa',49,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('244',NULL,'Jorge','Morillo Cuadrado',49,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('245',NULL,'Javier Roberto','Ortiz Galvis',44,NULL,'DIMAR-División de Litorales y Areas Marinas',1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('246',NULL,'Paula Judith','Rojas',20,NULL,NULL,1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('247',NULL,'Fernando','Luna',48,NULL,NULL,1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('248',NULL,'Emerson Esneider','Espitia Espitia',49,NULL,NULL,1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('249',NULL,'Ernesto','Durán',40,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('25',NULL,'Orlando','Perdomo Quezada',40,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('250',NULL,'Julio','Poveda',44,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('251',NULL,'Jaime','Moreno',44,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('252',NULL,'Fair','Robledo',44,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('253',NULL,'Cesar','Garzón Marenco',49,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('254',NULL,'Jorge','Padilla',49,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('256',NULL,'Jeimmy','Melo',27,NULL,NULL,20,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('257',NULL,'Natalia','Escobar',NULL,NULL,NULL,40,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('258',NULL,'Erika','Gutiérrez',NULL,NULL,NULL,37,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('259',NULL,'Héctor','Chaux Campo',48,NULL,NULL,69,NULL,NULL,NULL,NULL,'PE',NULL,'e-mail_1','e-mail_2'),
 ('26',NULL,'Jaime','Hernández Devia',40,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('260',NULL,'Jorge','Tovar',20,NULL,NULL,1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('261',NULL,'Marcela','Duarte',48,NULL,NULL,59,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('262',NULL,'Juan ','Rueda',49,NULL,NULL,1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('263',NULL,'Ingrid','Jiménez',21,NULL,NULL,40,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('264',NULL,'Eugenia','Escarria',21,NULL,NULL,26,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('265',NULL,'Alba','Fonseca',21,NULL,NULL,38,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('266',NULL,'Isabel','Ávila',21,NULL,NULL,18,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('267',NULL,'Germán','Soler',20,NULL,NULL,16,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('268',NULL,'Georgina','Flores',48,NULL,NULL,1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('269',NULL,'Efraín','Rodríguez Rubio',41,NULL,'CCCP-Director Científico Área Oceanografía Operacional',1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('27',NULL,'Jairo','Calle',48,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('270',NULL,'Sandra Liliana de La Esperanza','Franco',48,NULL,NULL,1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('271',NULL,'Silvio Andrés','Ordóñez',31,NULL,NULL,34,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('272',NULL,'Martha Lucero','Bastidas',31,NULL,NULL,34,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('273',NULL,'Andrea','Santa Ríos',28,NULL,NULL,70,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('274',NULL,'Hernán Darío','Zamora',32,NULL,NULL,43,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('275',NULL,'Josué Alfredo','Montaña',38,NULL,NULL,20,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('276',NULL,'José Francisco','Torres ',NULL,NULL,NULL,71,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('277',NULL,'Guillermo Enrique','Galindo',NULL,NULL,NULL,72,NULL,NULL,NULL,NULL,'EC',NULL,'e-mail_1','e-mail_2'),
 ('278',NULL,'José Augusto','Valencia',20,NULL,NULL,37,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('279',NULL,'Catherine','Díaz Chito',31,NULL,NULL,34,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('28',NULL,'Guillermo','Zambrano',48,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('280',NULL,'Carlos','Ruiz Tascón',49,NULL,'',1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('281',NULL,'Anderson','Lemus',49,NULL,NULL,1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('282',NULL,'Yaneth','Morales',20,NULL,NULL,26,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('283',NULL,'Tulia Isabel','Martínez',20,NULL,NULL,37,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('284',NULL,'Claudia','Dagua',31,NULL,NULL,34,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('285',NULL,'José Luis','Valencia',46,NULL,NULL,73,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('286',NULL,'Luz Jenny','Aguirre Tobón',46,NULL,NULL,74,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('287',NULL,'Ernesto','Guzmán Jr.',46,NULL,NULL,74,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('288',NULL,'Carolina','García',20,NULL,NULL,16,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('289',NULL,'Enrique','Rojas',38,NULL,NULL,20,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('29',NULL,'Rodrigo','Ferreira',48,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('290',NULL,'Hermann Aicardo','León Rincón',44,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('291',NULL,'David','Beltrán Peñaranda',49,NULL,NULL,1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('292',NULL,'Edgar','Pérez Porras',49,NULL,'CCCP-Auxiliar de Laboratorio de Química',1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('293',NULL,'Jeannet','León',NULL,NULL,NULL,72,NULL,NULL,NULL,NULL,'EC',NULL,'e-mail_1','e-mail_2'),
 ('294',NULL,'Julio César','Herrera',20,NULL,NULL,18,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('295',NULL,'Oscar','Martinez R.',NULL,NULL,NULL,40,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('296',NULL,'Milena','Lozano',21,NULL,NULL,36,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('297',NULL,'Jorge','Donoso',NULL,NULL,NULL,75,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('298',NULL,'Elizabeth','Hernández O.',21,NULL,NULL,18,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('299',NULL,'Alba Marina','Cobo V.',21,NULL,NULL,37,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('3',NULL,'Gustavo','Guardo',48,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('30',NULL,'Alfonso','Clavijo',48,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('300',NULL,'Juan Miguel','Camacho Arenas',49,NULL,'',1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('301',NULL,'Alex Enrique','Palomino Cadena',49,NULL,'',1,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('302',NULL,'Tatiana','Espinosa Montoya',29,NULL,NULL,41,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('303',NULL,'Juan Carlos','Acosta',44,NULL,NULL,3,NULL,NULL,NULL,NULL,'CO',NULL,NULL,NULL),
 ('304',NULL,'Rafael Ricardo','Torres Parra',44,NULL,NULL,3,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('305',NULL,'Ricardo José','Molares Babra',44,NULL,NULL,3,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('306',NULL,'Alejandro','Muñoz Vargas',49,NULL,NULL,3,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('307',NULL,'Alfredo','Gutiérrez',49,NULL,NULL,3,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('308',NULL,'Cesar','Echeverri',49,NULL,NULL,3,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('309',NULL,'Diego','Villate Daza',49,NULL,NULL,3,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('31',NULL,'Ernesto','Barriga',37,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('310',NULL,'Federico','Castillo',49,NULL,NULL,3,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('311',NULL,'Hector','Calderón Silva',49,NULL,NULL,3,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('312',NULL,'Jaime','Padilla Almeyda',49,NULL,NULL,3,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('313',NULL,'Jairo','González Paternina',49,NULL,NULL,3,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('314',NULL,'José','Llinas',49,NULL,NULL,3,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('315',NULL,'Julio','Blanco Algarín',49,NULL,NULL,3,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('316',NULL,'Libardo','Rodríguez Cala ',49,NULL,NULL,3,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('317',NULL,'Manfredo','Arrieta Díaz',49,NULL,NULL,3,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('318',NULL,'Mauricio','Olivares Lastra',49,NULL,NULL,3,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('319',NULL,'Miguel','Martínez Ricardo',49,NULL,NULL,3,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('32',NULL,'Iván','Guerrero',21,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('320',NULL,'William','Castro Pizarro',49,NULL,NULL,3,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('321',NULL,'Tatiana','Vanegas Jurado',1,NULL,NULL,3,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('322',NULL,'Gladis','Bernal',14,NULL,NULL,3,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('323',NULL,'Heiner','Olaya',14,NULL,NULL,3,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('324',NULL,'Carlos','Parra',3,NULL,NULL,3,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('325',NULL,'Juan Pablo','Bustamante Visbal',48,NULL,NULL,3,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('326',NULL,'Gustavo','Tous Herazo',48,NULL,NULL,3,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('327',NULL,'Hugo Javier','Llamas',48,NULL,NULL,3,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('328',NULL,'Carlos Alberto','Andrade',14,NULL,NULL,3,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('329',NULL,'Mary Luz','Páez',14,NULL,NULL,3,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('33',NULL,'Vicente','Rodríguez',21,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('330',NULL,'Wilmer Alonso','Cárdenas',55,NULL,NULL,3,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('331',NULL,'Andrés','Zambrano G.',44,NULL,NULL,13,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('332',NULL,'Carlos','Urbano Montes',44,NULL,NULL,13,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('333',NULL,'Carlos A.','Romero B.',44,NULL,NULL,13,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('334',NULL,'Cesar Augusto','Vargas Turizo',44,NULL,NULL,13,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('335',NULL,'Gary','González Núñez',44,NULL,NULL,13,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('336',NULL,'Gerrmán Augusto','Escobar Olaya',44,NULL,NULL,13,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('337',NULL,'Jairo','Orobio Sánchez',44,NULL,NULL,13,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('338',NULL,'José Manuel','Plazas Moreno',44,NULL,NULL,13,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('339',NULL,'Juan Carlos','Gómez López',44,NULL,NULL,13,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('34',NULL,'Arturo','Bermúdez',22,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('340',NULL,'Leonardo','Marriaga Rocha',44,NULL,NULL,13,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('341',NULL,'Mario','Cely Charris',44,NULL,NULL,13,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('342',NULL,'Nelson Enrique','Murillo Gómez',44,NULL,NULL,13,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('343',NULL,'Pedro Javier','Prada Rueda',44,NULL,NULL,13,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('344',NULL,'Victor','Masson Fiallos',44,NULL,NULL,13,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('345',NULL,'Martha','Cadena',38,NULL,NULL,20,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('346',NULL,'Andrés','Ortiz',21,NULL,NULL,37,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('347',NULL,'Juan David','Acevedo Acosta',21,NULL,NULL,37,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('348',NULL,'Madeleine','Barona',21,NULL,NULL,37,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('349',NULL,'Carlos Alejandro','Escobar',4,NULL,NULL,38,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('35',NULL,'Efraín','Ángel Cárdenas',20,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('350',NULL,'Jesús Alberto','Pérez',4,NULL,NULL,38,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('351',NULL,'Liliana','Velázquez Montoya',14,NULL,NULL,38,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('352',NULL,'W.','Benavides',44,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('353',NULL,'Angélica','Mejía',1,NULL,NULL,53,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('354',NULL,'Hernán Alejandro','Reyes Rivas',14,NULL,NULL,68,NULL,NULL,NULL,NULL,'CH',NULL,'e-mail_1','e-mail_2'),
 ('355',NULL,'Andrés Felipe','Velásquez Bran',49,NULL,NULL,76,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('356',NULL,'Cristhian','Arzuza Monterrosa',49,NULL,NULL,76,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('357',NULL,'Guido','Herrera Vásquez',49,NULL,NULL,76,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('358',NULL,'Hermes','Palomino',49,NULL,NULL,76,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('359',NULL,'Carlos','Pinzón Llorach',49,NULL,NULL,77,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('36',NULL,'Jaime','Prada',38,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('360',NULL,'Juan','Ortiz Buitrago',49,NULL,NULL,77,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('361',NULL,'Sadid','Latandret Solana',49,NULL,NULL,77,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('362',NULL,'Andrés','Orejarena',21,NULL,NULL,77,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('363',NULL,'José','Iriarte',55,NULL,NULL,77,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('364',NULL,'Jesús','Peñaranda Cabarcas',49,NULL,NULL,78,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('365',NULL,'Oscar','Tascón Vásquez',49,NULL,NULL,78,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('366',NULL,'Wilson','González Noreña',49,NULL,NULL,78,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('367',NULL,'Ángelo','Sartori Neto',28,NULL,NULL,79,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('368',NULL,'Jairo','Vargas',4,NULL,NULL,79,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('369',NULL,'José Antonio','Moreira Lima',5,NULL,NULL,79,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('37',NULL,'Alfonso','Lozano Julio',44,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('370',NULL,'Robert','Catalano',14,NULL,NULL,80,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('371',NULL,'David R.','Walsh',5,NULL,NULL,80,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('372',NULL,'Samuel','Witt Berry',5,NULL,NULL,80,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('38',NULL,'Jorge','Orjuela Pérez',44,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('39',NULL,'David René','Moreno',40,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('4',NULL,'Armando','Hernández',20,NULL,NULL,50,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('40',NULL,'Darío','De la Torre',40,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('41',NULL,'Jean','Allain',21,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('42',NULL,'Nicolás','Paz',21,NULL,NULL,28,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('43',NULL,'Tito','Machado',21,NULL,NULL,28,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('44',NULL,'Jorge','Thous',21,NULL,NULL,29,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('45',NULL,'Sebastián','San Juan',21,NULL,NULL,29,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('46',NULL,'Domingo','Ramos',48,NULL,NULL,29,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('47',NULL,'Héctor','Egel',48,NULL,NULL,29,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('48',NULL,'Luis','Del Castillo',48,NULL,NULL,29,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('49',NULL,'Jorge','Monroy',21,NULL,NULL,53,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('5',NULL,'Rubi','Mejia',48,NULL,NULL,37,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('50',NULL,'José Ignacio','Borrero',45,NULL,NULL,37,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('52',NULL,'Alfonso','Hernández',23,NULL,NULL,37,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('53',NULL,'Jaime','Cantera',21,NULL,NULL,37,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('54',NULL,'Fernando','Castro',21,NULL,NULL,37,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('55',NULL,'Jairo','Betancourt',21,NULL,NULL,37,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('56',NULL,'Efraín','Rubio',21,NULL,NULL,37,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('57',NULL,'Américo','Quintero',21,NULL,NULL,37,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('58',NULL,'Rafael','Steer Ruiz',44,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('59',NULL,'Ricardo','Parra Suárez',40,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('6',NULL,'Francisco','Pineda',20,NULL,NULL,37,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('60',NULL,'Bertha Cecilia','De Monsalve',21,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('61',NULL,'Consuelo','Carbonell',21,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('62',NULL,'David','Cortesero Olea',48,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('63',NULL,'Oswaldo','Mirazalde Vanegas',NULL,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('64',NULL,'Narda','Nates',NULL,NULL,NULL,53,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('65',NULL,'Iván','Rey',NULL,NULL,NULL,53,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('66',NULL,'Jorge','Trujillo Camacho',NULL,NULL,NULL,53,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('67',NULL,'Marco Antonio','Gómez',48,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('68',NULL,'Patrick','Lesueur',24,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('69',NULL,'Antonio','Bonfante',49,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('7',NULL,'Yesid','Ponce',48,NULL,NULL,51,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('70',NULL,'Hernando','Llamas',NULL,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('71',NULL,'Plinio','Romero',NULL,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('72',NULL,'Rodrigo','Díaz Granados',NULL,NULL,NULL,35,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('73',NULL,'Hernando','Correa',NULL,NULL,NULL,35,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('74',NULL,'Tomás','García',NULL,NULL,NULL,35,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('75',NULL,'Miguel','De Luque',NULL,NULL,NULL,35,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('76',NULL,'Luis','Obregón',NULL,NULL,NULL,35,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('77',NULL,'Martha','Muñoz',NULL,NULL,NULL,35,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('78',NULL,'Omar','Del Río',49,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('79',NULL,'Álvaro','González Hernández',NULL,NULL,NULL,54,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('8',NULL,'Jairo','Sánchez',48,NULL,NULL,42,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('80',NULL,'Gabriel','Meidinder',24,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('81',NULL,'Rubén A.','Cobariza',44,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('82',NULL,'Eusebio','Cabrales',44,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('83',NULL,'Francisco','Castillo',20,NULL,NULL,3,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('84',NULL,'Luis','Mendoza',25,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('85',NULL,'Amparo','Molina',24,NULL,NULL,3,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('86',NULL,'Mark','Elhayar',24,NULL,NULL,3,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('87',NULL,'Carmen','Parada',21,NULL,NULL,42,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('88',NULL,'Jorge E.','García Riaño',38,NULL,NULL,55,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('89',NULL,'Hugo','Cárdenas',38,NULL,NULL,55,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('9',NULL,'Harold','Santa Cruz Moncayo',40,NULL,NULL,49,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('90',NULL,'Liliana','Marín',NULL,NULL,NULL,42,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('91',NULL,'William Fernando','Parra',21,NULL,NULL,53,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('92',NULL,'Jesús','Garay',21,NULL,NULL,3,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('93',NULL,'Rubén','Serrano',44,NULL,NULL,3,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('94',NULL,'Oscar','Neira',49,NULL,NULL,3,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('95',NULL,'José','Godoy',49,NULL,NULL,3,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('97',NULL,'Luis','Peña',38,NULL,NULL,55,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('98',NULL,'Guillermo','Pulido',38,NULL,NULL,55,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2'),
 ('99',NULL,'Gabriel','Luna',21,NULL,NULL,53,NULL,NULL,NULL,NULL,'CO',NULL,'e-mail_1','e-mail_2');
/*!40000 ALTER TABLE `inv_chief_scientist` ENABLE KEYS */;
